### ISSUE TITLE
Race in chunk downloader?

### ISSUE THREAD

**Issue by SteveAlexander** [snowflakedb/snowflake-sqlalchemy#116]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

Python 3.7.3

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Darwin-18.6.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 

```
snowflake-connector-python 1.8.1
snowflake-ingest           0.9.1
snowflake-sqlalchemy       1.1.14
SQLAlchemy                 1.3.6
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Performing a select with `fetchall()` on the result set, as a regular part of my product's data processing. I'll figure out a test case, but I don't have one just yet.

The error occurs perhaps once every 40-50 runs.

5. What did you expect to see?

No error.

6. What did you see instead?

```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 753, in fetchone
    row = next(self._current_chunk_row)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1216, in fetchall
    e, None, None, self.cursor, self.context
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1468, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1211, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1161, in _fetchall_impl
    return self.cursor.fetchall()
  File "/anaconda3/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 828, in fetchall
    row = self.fetchone()
  File "/anaconda3/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 759, in fetchone
    next_chunk = self._chunk_downloader.next_chunk()
  File "/anaconda3/lib/python3.7/site-packages/snowflake/connector/chunk_downloader.py", line 176, in next_chunk
    raise self._downloader_error
  File "/anaconda3/lib/python3.7/site-packages/snowflake/connector/chunk_downloader.py", line 130, in _download_chunk
    with self._chunk_locks[idx]:
KeyError: 1
```

7. Can you set logging to DEBUG and collect the logs?

Problem appears to not occur when logs are being collected. Suggests it may be a race condition.

**Comment by SteveAlexander** [comment]
ok, managed to get it to fail, after a much longer time than without debugging logs.

Looking through the logs, the problem seems to occur after a dropped connection:

```
2019-09-17 17:54:15,008 - Thread-366 connectionpool.py:238 - _get_conn() - INFO - Resetting dropped connection: sfc-ie-ds1-2-customer-stage.s3.amazonaws.com
2019-09-17 17:54:15,009 - Thread-368 connectionpool.py:238 - _get_conn() - INFO - Resetting dropped connection: sfc-ie-ds1-2-customer-stage.s3.amazonaws.com
2019-09-17 17:54:15,009 - Thread-367 connectionpool.py:238 - _get_conn() - INFO - Resetting dropped connection: sfc-ie-ds1-2-customer-stage.s3.amazonaws.com
2019-09-17 17:54:15,085 - Thread-367 ssl_wrap_socket.py:390 - ssl_wrap_socket_with_ocsp() - DEBUG - OCSP Mode: FAIL_OPEN, OCSP response cache file name: None
2019-09-17 17:54:15,085 - Thread-367 ocsp_snowflake.py:379 - reset_ocsp_response_cache_uri() - DEBUG - ocsp_response_cache_uri: file:///Users/steve/Library/Caches/Snowflake/ocsp_response_cache.json
2019-09-17 17:54:15,085 - Thread-367 ocsp_snowflake.py:381 - reset_ocsp_response_cache_uri() - DEBUG - OCSP_VALIDATION_CACHE size: 53
2019-09-17 17:54:15,085 - Thread-367 ocsp_snowflake.py:206 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP response cache server is enabled: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json
2019-09-17 17:54:15,085 - Thread-367 ocsp_snowflake.py:240 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP dynamic cache server RETRY URL: None
2019-09-17 17:54:15,085 - Thread-368 ssl_wrap_socket.py:390 - ssl_wrap_socket_with_ocsp() - DEBUG - OCSP Mode: FAIL_OPEN, OCSP response cache file name: None
2019-09-17 17:54:15,085 - Thread-368 ocsp_snowflake.py:379 - reset_ocsp_response_cache_uri() - DEBUG - ocsp_response_cache_uri: file:///Users/steve/Library/Caches/Snowflake/ocsp_response_cache.json
2019-09-17 17:54:15,085 - Thread-368 ocsp_snowflake.py:381 - reset_ocsp_response_cache_uri() - DEBUG - OCSP_VALIDATION_CACHE size: 53
2019-09-17 17:54:15,086 - Thread-368 ocsp_snowflake.py:206 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP response cache server is enabled: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json
```

then lots of SSL reconnection stuff, followed eventually by Thread-368 running into a problem:

```
2019-09-17 17:54:15,293 - Thread-368 network.py:913 - _use_requests_session() - DEBUG - Active requests sessions: 2, idle: 2
2019-09-17 17:54:15,293 - Thread-368 chunk_downloader.py:119 - _download_chunk() - DEBUG - finished getting the result set 3: https://sfc-ie-ds1-2-customer-stage.s3.amazonaws.com/3gn2-s-iess2161/results/018ef376-00d7-f913-0000-21a900090482_0/main/data_0_3_0?x-amz-server-side-encryption-customer-algorithm=AES256&response-content-encoding=gzip&AWSAccessKeyId=xxx&Expires=1568760854&Signature=xxx%3D
2019-09-17 17:54:15,293 - Thread-368 chunk_downloader.py:141 - _download_chunk() - ERROR - Failed to fetch the large result set chunk 3/15
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/snowflake/connector/chunk_downloader.py", line 130, in _download_chunk
    with self._chunk_locks[idx]:
KeyError: 2
```

**Comment by smtakeda** [comment]
Can you please try the latest Python Connector 1.9.0? _chunk_locks was removed and instead a single lock is used to protect the download cache.

**Comment by SteveAlexander** [comment]
Thanks, that seems to have fixed it
