### ISSUE TITLE
[Version 1.1.16] Import path `azure.storage.blob`; cannot import name 'BlockBlobService'

### ISSUE THREAD

**Issue by arthurdysart** [snowflakedb/snowflake-sqlalchemy#127]
1. What version of Python are you using (`python --version`)?
> Python 3.6.8

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
> Darwin-18.7.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 
> Package                    Version
> -------------------------- ---------
> asn1crypto                 1.2.0
> azure-common               1.1.23
> azure-core                 1.0.0
> azure-storage-blob         12.0.0
> boto3                      1.9.253
> botocore                   1.12.253
> certifi                    2019.9.11
> cffi                       1.13.1
> chardet                    3.0.4
> cryptography               2.8
> docutils                   0.15.2
> future                     0.18.2
> idna                       2.8
> ijson                      2.5.1
> isodate                    0.6.0
> jmespath                   0.9.4
> msrest                     0.6.10
> oauthlib                   3.1.0
> oscrypto                   1.1.0
> pip                        19.3.1
> pycparser                  2.19
> pycryptodomex              3.9.0
> PyJWT                      1.7.1
> pyOpenSSL                  19.0.0
> python-dateutil            2.8.0
> pytz                       2019.3
> requests                   2.22.0
> requests-oauthlib          1.2.0
> s3transfer                 0.2.1
> setuptools                 41.6.0
> six                        1.12.0
> snowflake-connector-python 2.0.2
> snowflake-sqlalchemy       1.1.16
> SQLAlchemy                 1.3.10
> urllib3                    1.25.6
> wheel                      0.33.6
> 

4. What did you do? If possible, provide a recipe for reproducing the error.A complete runnable program is good.

Installed `snowflake-connector-python` and `snowflake-sqlalchemy`:
```bash
virtualenv -p python3 venv-snowflake-issue
. venv-snowflake-issue/bin/activate
pip3 install --upgrade snowflake-sqlalchemy snowflake-connector-python
python3 -c 'from snowflake.sqlalchemy import URL'
```

5. What did you expect to see?

6. What did you see instead?
> Module import path `azure.storage.blob` appears incorrect and yields following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/sqlalchemy/__init__.py", line 8, in <module>
    from . import snowdialect
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/sqlalchemy/snowdialect.py", line 25, in <module>
    from snowflake.connector.constants import UTF8
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/connection.py", line 44, in <module>
    from .cursor import SnowflakeCursor, LOG_MAX_QUERY_LENGTH
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 29, in <module>
    from .file_transfer_agent import (SnowflakeFileTransferAgent)
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/file_transfer_agent.py", line 20, in <module>
    from .azure_util import SnowflakeAzureUtil
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/azure_util.py", line 9, in <module>
    from azure.storage.blob import BlockBlobService
ImportError: cannot import name 'BlockBlobService'
```

7. Can you set logging to DEBUG and collect the logs?

```
2019-10-31 23:59:42,181 - MainThread ssl_wrap_socket.py:86 - inject_into_urllib3() - DEBUG - Injecting ssl_wrap_socket_with_ocsp
2019-10-31 23:59:42,192 - MainThread auth.py:71 - <module>() - DEBUG - cache directory: /Users/main-user/Library/Caches/Snowflake
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/sqlalchemy/__init__.py", line 8, in <module>
    from . import snowdialect
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/sqlalchemy/snowdialect.py", line 25, in <module>
    from snowflake.connector.constants import UTF8
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/connection.py", line 44, in <module>
    from .cursor import SnowflakeCursor, LOG_MAX_QUERY_LENGTH
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 29, in <module>
    from .file_transfer_agent import (SnowflakeFileTransferAgent)
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/file_transfer_agent.py", line 20, in <module>
    from .azure_util import SnowflakeAzureUtil
  File "/Users/main-user/local-test/lib/python3.6/site-packages/snowflake/connector/azure_util.py", line 9, in <module>
    from azure.storage.blob import BlockBlobService
ImportError: cannot import name 'BlockBlobService'
```

**Comment by oh54** [comment]
I ran into the same issue.

```bash
pip install snowflake-sqlalchemy
```
also installs the latest version of azure storage blob (currently azure-storage-blob==12.0.0).

Then trying to import anything from snowflake.sqlalchemy leads to ImportError: cannot import name 'BlockBlobService'.

I uninstalled everything, then manually installed the previous version of azure-storage-blob before installing snowflake-sqlalchemy.
```bash
pip install azure-storage-blob==2.1.0
pip install snowflake-sqlalchemy
```

This resolved the problem.

**Comment by arthurdysart** [comment]
Rolling back snowflake and azure package versions also worked for me:
```
azure-common==1.1.23
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
snowflake-connector-python==1.8.2
snowflake-sqlalchemy==1.1.14
```

I'd consider this a temporary fix though. Hopefully the import paths can be fixed soon

**Comment by snowstakeda** [comment]
https://github.com/snowflakedb/snowflake-connector-python/issues/225
We'll release 2.0.3 soon.

**Comment by snowstakeda** [comment]
Released.
