### ISSUE TITLE
Calling str on custom_types throws Exception

### ISSUE THREAD

**Issue by villebro** [snowflakedb/snowflake-sqlalchemy#132]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
`Python 3.7.4`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
`Darwin-18.7.0-x86_64-i386-64bit`

3. What are the component versions in the environment (`pip list`)? 
```
Package                    Version   Location                
-------------------------- --------- ------------------------
asn1crypto                 1.2.0     
azure-common               1.1.23    
azure-storage-blob         2.1.0     
azure-storage-common       2.1.0     
boto3                      1.10.15   
botocore                   1.13.15   
certifi                    2019.9.11 
cffi                       1.13.2    
chardet                    3.0.4     
Click                      7.0       
cryptography               2.8       
decorator                  4.4.1     
docutils                   0.15.2    
future                     0.18.2    
idna                       2.8       
ijson                      2.5.1     
jmespath                   0.9.4     
numpy                      1.17.2    
oscrypto                   1.1.0     
pbr                        5.4.3     
pip                        19.2.3    
pip-tools                  4.2.0     
pyarrow                    0.14.1    
pycparser                  2.19      
pycryptodomex              3.9.2     
PyJWT                      1.7.1     
pyOpenSSL                  19.0.0    
python-dateutil            2.8.0     
pytz                       2019.3    
requests                   2.22.0    
s3transfer                 0.2.1     
setuptools                 41.2.0    
six                        1.13.0    
snowflake-connector-python 2.0.3     
snowflake-sqlalchemy       1.1.16    
SQLAlchemy                 1.3.11    
sqlalchemy-migrate         0.13.0    
SQLAlchemy-Utils           0.34.2    
sqlparse                   0.3.0     
sqltask                    0.5.2     /Users/ville/dev/sqltask
Tempita                    0.5.2     
urllib3                    1.24.3    
wheel                      0.33.6
```

4. What did you do?
```python
from snowflake.sqlachemy import custom_types

tinyint = custom_types.TINYINT()
timestamp_ntz = custom_types.TIMESTAMP_NTZ()

tinyint_str = str(tinyint)  # this works
timestamp_ntz_str = str(timestamp_ntz)  # this doesn't
```

5. What did you expect to see?
calling `str()` on snowflake types should work similar to how regular SqlAlchemy types do.

6. What did you see instead?
```
Traceback (most recent call last):
  File "/Users/ville/.local/share/virtualenvs/adm-C7TUfBSf/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 88, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'GenericTypeCompiler' object has no attribute 'visit_TIMESTAMP_NTZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ville/.local/share/virtualenvs/adm-C7TUfBSf/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 607, in __str__
    return str(self.compile())
  File "/Users/ville/.local/share/virtualenvs/adm-C7TUfBSf/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 590, in compile
    return dialect.type_compiler.process(self)
  File "/Users/ville/.local/share/virtualenvs/adm-C7TUfBSf/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 400, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/ville/.local/share/virtualenvs/adm-C7TUfBSf/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 90, in _compiler_dispatch
    raise exc.UnsupportedCompilationError(visitor, cls)
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x114661d90> can't render element of type <class 'snowflake.sqlalchemy.custom_types.TIMESTAMP_NTZ'> (Background on this error at: http://sqlalche.me/e/l7de)
```

**Comment by keller00** [comment]
This used to work months ago. SQLAlchemy must have reworked their internals.

**Comment by keller00** [comment]
I have fixed the issue, it'll be included in the next release
