### ISSUE TITLE
fetchall() Exception: Attempted to add log when TelemetryClient is closed

### ISSUE THREAD

**Issue by insightfulquery** [snowflakedb/snowflake-sqlalchemy#183]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)? 3.7.3

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)? Windows-10-10.0.18362-SP0

3. What are the component versions in the environment (`pip list`)? 
absl-py                            0.7.1
agate                              1.6.1
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.2
asn1crypto                         1.3.0
astor                              0.7.1
astroid                            2.2.5      
astropy                            3.1.2
atomicwrites                       1.3.0
attrs                              19.1.0
Authlib                            0.14.3
azure-common                       1.1.25
azure-storage-blob                 2.1.0
azure-storage-common               2.1.0
Babel                              2.6.0
backcall                           0.1.0
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.7.1
bitarray                           0.8.3
bkcharts                           0.2
bleach                             3.1.0
bokeh                              1.0.4
boto                               2.49.0
boto3                              1.9.253
botocore                           1.12.253
Bottleneck                         1.2.1
cachetools                         4.0.0
certifi                            2020.4.5.1
cffi                               1.12.2
chardet                            3.0.4
Click                              7.0
click-plugins                      1.1.1
cligj                              0.5.0
cloudpickle                        0.8.0
clyent                             1.2.2
colorama                           0.4.1
comtypes                           1.1.7
conda                              4.8.3
conda-build                        3.17.8
conda-package-handling             1.3.11
conda-verify                       3.1.1
contextlib2                        0.5.5
cryptography                       2.6.1
cycler                             0.10.0
Cython                             0.29.6     
cytoolz                            0.9.0.1
dask                               1.1.4
dbt                                0.16.1
dbt-bigquery                       0.16.1
dbt-core                           0.16.1
dbt-postgres                       0.16.1
dbt-redshift                       0.16.1
dbt-snowflake                      0.16.1
decorator                          4.4.0
defusedxml                         0.5.0
distributed                        1.26.0
docutils                           0.14
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.0.2
filelock                           3.0.10
Fiona                              1.8.4
Flask                              1.0.2      
fsspec                             0.7.4
future                             0.17.1
gast                               0.2.2
GDAL                               2.3.3
geopandas                          0.6.1
gevent                             1.4.0
glob2                              0.6
google-api-core                    1.16.0
google-auth                        1.11.3
google-auth-oauthlib               0.4.1
google-cloud-bigquery              1.24.0
google-cloud-core                  1.3.0
google-resumable-media             0.5.0
googleapis-common-protos           1.6.0
googlemaps                         4.4.1
greenlet                           0.4.15
grpcio                             1.20.1
h5py                               2.9.0
heapdict                           1.0.0
hologram                           0.0.6
html5lib                           1.0.1
idna                               2.8
ijson                              2.6.1
imageio                            2.5.0
imagesize                          1.1.0
importlib-metadata                 0.0.0
ipykernel                          5.1.0
ipython                            7.4.0
ipython-genutils                   0.2.0
ipywidgets                         7.4.2
isodate                            0.6.0
isort                              4.3.16
itsdangerous                       1.1.0
jdcal                              1.4
jedi                               0.13.3
Jinja2                             2.10
jmespath                           0.9.5
joblib                             0.15.1
json-rpc                           1.13.0     
json5                              0.9.5
jsonschema                         3.0.1
jupyter                            1.0.0
jupyter-client                     5.2.4
jupyter-console                    6.0.0
jupyter-core                       4.4.0
jupyterlab                         0.35.4
jupyterlab-server                  0.2.0
Keras                              2.2.4
Keras-Applications                 1.0.7
Keras-Preprocessing                1.0.9
keyring                            18.0.0
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
leather                            0.3.3      
libarchive-c                       2.8
llvmlite                           0.28.0
locket                             0.2.0
Logbook                            1.5.3
lxml                               4.3.2
Markdown                           3.1
MarkupSafe                         1.1.1
matplotlib                         3.0.3
mccabe                             0.6.1
menuinst                           1.4.16
minimal-snowplow-tracker           0.0.2
mistune                            0.8.4
mkl-fft                            1.0.10
mkl-random                         1.0.2
mock                               4.0.2
more-itertools                     6.0.0
mpmath                             1.1.0
msgpack                            0.6.1
multipledispatch                   0.6.0
munch                              2.5.0
navigator-updater                  0.2.1
nbconvert                          5.4.1
nbformat                           4.4.0
networkx                           2.4
nltk                               3.4
nose                               1.3.7
notebook                           5.7.8
numba                              0.43.1
numexpr                            2.6.9
numpy                              1.16.2
numpydoc                           0.8.0
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           2.6.1
oscrypto                           1.2.0
packaging                          19.0
pandas                             0.24.2
pandas-gbq                         0.13.1
pandocfilters                      1.4.2
parsedatetime                      2.5
parso                              0.3.4      
partd                              0.3.10
path.py                            11.5.0
pathlib2                           2.3.3
patsy                              0.5.1
pep8                               1.7.1
pickleshare                        0.7.5
Pillow                             5.4.1
pip                                19.0.3
pkginfo                            1.5.0.1
pluggy                             0.9.0
ply                                3.11
progress                           1.5
prometheus-client                  0.6.0
prompt-toolkit                     2.0.9
protobuf                           3.7.1
psutil                             5.6.1
psycopg2-binary                    2.8.4
py                                 1.8.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pycryptodomex                      3.9.7
pycurl                             7.43.0.2
pydata-google-auth                 0.3.0
pyflakes                           2.1.1
Pygments                           2.3.1
PyJWT                              1.7.1
pylint                             2.3.1
pyodbc                             4.0.26
pyOpenSSL                          19.0.0
pyparsing                          2.3.1
pyproj                             1.9.6
pyreadline                         2.1
pyrsistent                         0.14.11
PySocks                            1.6.8
pytest                             4.3.1
pytest-arraydiff                   0.3
pytest-astropy                     0.5.0
pytest-doctestplus                 0.3.0
pytest-logbook                     1.2.0
pytest-openfiles                   0.3.2
pytest-remotedata                  0.3.1
python-dateutil                    2.8.0
python-slugify                     4.0.0
pytimeparse                        1.1.8      
pytz                               2018.9
PyWavelets                         1.0.2
pywin32                            223
pywinpty                           0.5.5
PyYAML                             5.1
pyzmq                              18.0.0
QtAwesome                          0.5.7
qtconsole                          4.4.3
QtPy                               1.7.0
requests                           2.22.0
requests-oauthlib                  1.3.0
rope                               0.12.0
rsa                                4.0
Rtree                              0.8.3
ruamel-yaml                        0.15.46
s3transfer                         0.2.1
scikit-image                       0.14.2
scikit-learn                       0.20.3     
scipy                              1.2.1
seaborn                            0.9.0
Send2Trash                         1.5.0
setuptools                         40.8.0
Shapely                            1.6.4.post1
simple-salesforce                  1.1.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.14.0
snowballstemmer                    1.2.1
snowflake                          0.0.3
snowflake-connector-python         2.2.1
snowflake-sqlalchemy               1.2.3
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.8
Sphinx                             1.8.5
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.1.0
spyder                             3.3.3
spyder-kernels                     0.4.2
SQLAlchemy                         1.3.1
sqlparse                           0.3.1
statsmodels                        0.9.0
sympy                              1.3
tables                             3.5.1
tblib                              1.3.2
tensorboard                        1.13.1
tensorflow                         1.13.1
tensorflow-estimator               1.13.0
termcolor                          1.1.0
terminado                          0.8.1
testpath                           0.4.2
text-unidecode                     1.3
toolz                              0.9.0
tornado                            6.0.2      
tqdm                               4.31.1
traitlets                          4.3.2
typing-extensions                  3.7.4.1
unicodecsv                         0.14.1
urllib3                            1.24.1
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.16.1
wheel                              0.33.1
widgetsnbextension                 3.4.2
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.1
xlrd                               1.2.0
XlsxWriter                         1.1.5
xlwings                            0.15.4
xlwt                               1.3.0
zict                               0.1.4
zipp                               0.3.3

4. What did you do?
from sqlalchemy import create_engine
engine = create_engine(
	'snowflake://{user}:{password}@{account}/{database}/{schema}?warehouse={warehouse}&role={role}'.format(
		user=user_config.snowflake_credentials['username'],
		password=user_config.snowflake_credentials['password'],
		account='turnkeyvr.us-east-1',
		database=database,
		schema=schema,
		warehouse=warehouse,
		role=role
	)
)
conn = self.engine.connect()
sql = """
select ID, is_deleted, amount, probability, close_date, created_date
from staging.salesforce_history.opportunity
limit 100
"""
results = conn.execute(sql)
# So far so good. Next line raises exception:
x = result.fetchall()

5. What did you expect to see?
No output, just x populated with the results.

6. What did you see instead?
WARNING:snowflake.connector.telemetry:Failed to add log to telemetry.
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Insig\Anaconda3\lib\site-packages\snowflake\connector\telemetry.py", line 72, in try_add_log_to_batch
    self.add_log_to_batch(telemetry_data)
  File "C:\Users\Insig\Anaconda3\lib\site-packages\snowflake\connector\telemetry.py", line 59, in add_log_to_batch
    "Attempted to add log when TelemetryClient is closed")
Exception: Attempted to add log when TelemetryClient is closed

7. Can you set logging to DEBUG and collect the logs?
2020-07-15 14:11:30,847 - MainThread cursor.py:824 - fetchone() - DEBUG - Arrow BatchSize: 1
2020-07-15 14:11:30,851 - MainThread cursor.py:824 - fetchone() - DEBUG - Arrow chunk info: batchCount 1, columnCount 6, use_numpy: 0
2020-07-15 14:11:30,852 - MainThread cursor.py:824 - fetchone() - DEBUG - Current batch index: 0, rows in current batch: 100
2020-07-15 14:11:30,854 - MainThread cursor.py:824 - fetchone() - INFO - fetching data done
2020-07-15 14:11:30,855 - MainThread telemetry.py:74 - try_add_log_to_batch() - WARNING - Failed to add log to telemetry.
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Insig\Anaconda3\lib\site-packages\snowflake\connector\telemetry.py", line 72, in try_add_log_to_batch
    self.add_log_to_batch(telemetry_data)
  File "C:\Users\Insig\Anaconda3\lib\site-packages\snowflake\connector\telemetry.py", line 59, in add_log_to_batch
    "Attempted to add log when TelemetryClient is closed")
Exception: Attempted to add log when TelemetryClient is closed

**Comment by insightfulquery** [comment]
You might want to just close this one, it might be a weird fluke. It was throwing the exception, even after I restarted my python kernel in VSCode, but when I restarted the computer the error went away.

**Comment by insightfulquery** [comment]
Still seeing this on and off. Might be specific to my environment. Restarting always fixes it.
