### ISSUE TITLE
SNOW-307731: snowflake-sqlachemy - stacktrace from SQLAlchemy when using SQLAlchemy > 1.3.23

### ISSUE THREAD

**Issue by MikolajSedek** [snowflakedb/snowflake-sqlalchemy#219]
When trying to connect to Snowflake using a package with:

```
install_requires=[
        "snowflake-connector-python[pandas]==2.4.1",
        "snowflake-sqlalchemy==1.2.4"
    ],
```
I get a stacktrace from sqlachemy (shown in 7. LOGS below). The only way for us to avoid this problem is to downgrade SQLAlchemy to v.1.3.23 - then the problem is no longer present. The dependency for SQLAlchemy in snowflake-sqlachemy `setup.py` is sqlalchemy<2.0.0. This might be caused by https://github.com/sqlalchemy/sqlalchemy/issues/5645. Could you please check if you could reproduce and fix this bug?

Basic Questions:

1. Python 3.8.5

2. macOS-10.15.7-x86_64-i386-64bit

3. pip list: 

```
asn1crypto                 1.4.0
azure-common               1.1.26
azure-core                 1.12.0
azure-storage-blob         12.8.0
boto3                      1.17.38
botocore                   1.20.38
certifi                    2020.12.5
cffi                       1.14.5
chardet                    3.0.4
cryptography               3.4.7
finai-db-model-interface   0.3.5
greenlet                   1.0.0
idna                       2.10
isodate                    0.6.0
jmespath                   0.10.0
msrest                     0.6.21
numpy                      1.20.1
oauthlib                   3.1.0
oscrypto                   1.2.1
pandas                     1.1.5
pip                        21.0.1
pyarrow                    3.0.0
pycparser                  2.20
pycryptodomex              3.10.1
PyJWT                      2.0.1
pyOpenSSL                  19.1.0
python-dateutil            2.8.1
pytz                       2021.1
requests                   2.25.1
requests-oauthlib          1.3.0
s3transfer                 0.3.6
setuptools                 54.2.0
six                        1.15.0
snowflake-connector-python 2.4.1
snowflake-sqlalchemy       1.2.4
SQLAlchemy                 1.4.3
urllib3                    1.26.4

```

4. Connecting to SF and quering database using
`session.execute(query).cursor.fetch_pandas_batches()`

5. What did you expect to see?
Results in a pandas dataframe

6. What did you see instead?
Stacktrace from SQLAlchemy 

7. LOGS
```
Traceback (most recent call last):
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/src/tests/db_model_interface/test_feature_repository.py", line 334, in test_multigroup_feature_fetch
    result = repository.fetch_sample(3, feature_groups=[0, 3])
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/src/finai/db_model_interface/feature_repository.py", line 109, in fetch_sample
    feature_set = self._determine_feature_set(features, feature_groups, exclude_features)
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/src/finai/db_model_interface/feature_repository.py", line 212, in _determine_feature_set
    result.update(f for group in feature_groups for f in self.meta_cache.get_group_features(group))
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/src/finai/db_model_interface/feature_repository.py", line 212, in <genexpr>
    result.update(f for group in feature_groups for f in self.meta_cache.get_group_features(group))
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/src/finai/db_model_interface/feature_repository.py", line 86, in meta_cache
    self._meta_cache.refresh_cache()
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/src/finai/db_model_interface/feature_repository.py", line 47, in refresh_cache
    self.session.query(DictFeature)
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2665, in all
    return self._iter().all()
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1328, in all
    return self._allrows()
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1236, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1629, in _fetchall_impl
    return list(self.iterator)
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 111, in chunks
    fetch = cursor._raw_all_rows()
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/Users/mikolaj.sedek/PycharmProjects/DbModelInterface/venv2/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1697, in process
    value = parent_processor(value)
TypeError: expected bytes, str found

```

**Comment by omercloudinary** [comment]
when creating the engine, by any chance did you send the **convert_unicode** parameter?
`create_engine(connection_string, convert_unicode=True)`
because **convert_unicode**  is deprecated and caused me the exact same error.
removing that parameter solved my issue. just use
`create_engine(connection_string)`

**Comment by mixtoism** [comment]
I am having a similar, issue. I am not setting the convert_unicode in the create engine.
I have two ORM classes first one commits and queries just fine, the other commits fine, but it breaks when reading
