### ISSUE TITLE
SNOW-372138: AttributeError: module 'snowflake.sqlalchemy' has no attribute 'dialect'

### ISSUE THREAD

**Issue by benekastah** [snowflakedb/snowflake-sqlalchemy#229]
1. What version of Python are you using (`python --version`)?

Python 3.7.9

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Darwin-20.3.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 

```
Package                    Version
-------------------------- ---------
asn1crypto                 1.4.0
azure-common               1.1.27
azure-core                 1.15.0
azure-storage-blob         12.8.1
boto3                      1.17.99
botocore                   1.20.99
certifi                    2021.5.30
cffi                       1.14.5
chardet                    4.0.0
cryptography               3.4.7
greenlet                   1.1.0
idna                       2.10
importlib-metadata         4.5.0
isodate                    0.6.0
jmespath                   0.10.0
msrest                     0.6.21
oauthlib                   3.1.1
oscrypto                   1.2.1
pip                        21.1.2
pycparser                  2.20
pycryptodomex              3.10.1
PyJWT                      2.1.0
pyOpenSSL                  20.0.1
python-dateutil            2.8.1
pytz                       2021.1
requests                   2.25.1
requests-oauthlib          1.3.0
s3transfer                 0.4.2
setuptools                 47.1.0
six                        1.16.0
snowflake-connector-python 2.4.6
snowflake-sqlalchemy       1.2.4
SQLAlchemy                 1.4.19
typing-extensions          3.10.0.0
urllib3                    1.26.5
zipp                       3.4.1
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```python
#!/usr/bin/env python
from sqlalchemy import create_engine
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)

engine = create_engine(
    'snowflake://{user}:{password}@{account}/'.format(
        user='PAULHARPER',
        password='anj7ZkE-Dih7Ja4Bh9uDmzGU@gmJ',
        account='BKA55150',
    )
)
try:
    connection = engine.connect()
    results = connection.execute('select current_version()').fetchone()
    print(results[0])
finally:
    connection.close()
    engine.dispose()
```

5. What did you expect to see?

The Snowflake version.

6. What did you see instead?

```
2021-06-24 11:51:43,990 - MainThread ssl_wrap_socket.py:43 - inject_into_urllib3() - DEBUG - Injecting ssl_wrap_socket_with_ocsp
Traceback (most recent call last):
  File "snowflake.py", line 18, in <module>
    account=myaccount,
  File "<string>", line 2, in create_engine
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 636, in _get_entrypoint
    cls = registry.load(name)
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 341, in load
    return impl.load()
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/snowflake/sqlalchemy/__init__.py", line 8, in <module>
    from . import snowdialect
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/snowflake/sqlalchemy/snowdialect.py", line 27, in <module>
    from snowflake.connector.constants import UTF8
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/snowflake/connector/__init__.py", line 15, in <module>
    from .connection import SnowflakeConnection
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/snowflake/connector/connection.py", line 33, in <module>
    from .auth import Auth
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/snowflake/connector/auth.py", line 64, in <module>
    from .options import installed_keyring, keyring
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/snowflake/connector/options.py", line 11, in <module>
    import pkg_resources
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3261, in <module>
    @_call_aside
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3289, in _initialize_master_working_set
    for dist in working_set
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3289, in <genexpr>
    for dist in working_set
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2795, in activate
    declare_namespace(pkg)
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2302, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2235, in _handle_ns
    loader.load_module(packageName)
  File "/Users/paul/code/testytest/snowflake.py", line 18, in <module>
    account='BKA55150',
  File "<string>", line 2, in create_engine
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 636, in _get_entrypoint
    cls = registry.load(name)
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 330, in load
    return self.impls[name]()
  File "/Users/paul/code/testytest/venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 169, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'snowflake.sqlalchemy' has no attribute 'dialect'
```

7. Can you set logging to DEBUG and collect the logs?

Yes, debug logging was included.

**Comment by sfc-gh-mkeller** [comment]
@benekastah Could you please post how you setup your `virtualenv`? I tried running your code the following way:

`requirements.txt`:
```
asn1crypto==1.4.0
azure-common==1.1.27
azure-core==1.15.0
azure-storage-blob==12.8.1
boto3==1.17.99
botocore==1.20.99
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
cryptography==3.4.7
greenlet==1.1.0
idna==2.10
importlib-metadata==4.5.0
isodate==0.6.0
jmespath==0.10.0
msrest==0.6.21
oauthlib==3.1.1
oscrypto==1.2.1
pip==21.1.2
pycparser==2.20
pycryptodomex==3.10.1
PyJWT==2.1.0
pyOpenSSL==20.0.1
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
requests-oauthlib==1.3.0
s3transfer==0.4.2
setuptools==47.1.0
six==1.16.0
snowflake-connector-python==2.4.6
snowflake-sqlalchemy==1.2.4
SQLAlchemy==1.4.19
typing-extensions==3.10.0.0
urllib3==1.26.5
zipp==3.4.1
```

`code.py`:
```python
#!/usr/bin/env python
from sqlalchemy import create_engine
import logging
import os
from snowflake.sqlalchemy import URL

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)

engine = create_engine(
        URL(
            account='...',
            user='...',
            password='...',
            host='...',
            port='...',
            database='...',
            schema='...',
        )
)
try:
    connection = engine.connect()
    results = connection.execute('select current_version()').fetchone()
    print(results[0])
finally:
    connection.close()
    engine.dispose()
```

Setup and run test:
```bash
/tmp/test
<$> virtualenv -p python3.6
/tmp/test
<$> source venv/bin/activate
/tmp/test
<$> pip install -U pip setuptools wheel
/tmp/test
<$> pip install -r requirements.txt
/tmp/test
<$> python --version --version
Python 3.6.13 (default, Mar 16 2021, 18:39:10)
[GCC Apple LLVM 12.0.0 (clang-1200.0.32.29)]
/tmp/test
<$> python code.py
```

And this worked for me without issues.

**Comment by sfc-gh-aling** [comment]
hey @benekastah, I can reproduce the issue by following your instructions.

The root cause is that the name of your scripts is "snowflake.py" (as indicated by your logging) which conflicts the `snowflake` namespace leading to an old version of `setuptools`(v47.1.0 as per your dev requirement) unable to load module by name correctly.

to fix the issue, there're two options:

1. rename your script NOT to use `snowflake`.
2. or upgrade `setuptools` package to be >= 51.2.0 (see their [changelog](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#id252)) where they have improved the namespace declaration logic.

Please let us know if there's anything else we could help with.

**Comment by sfc-gh-aling** [comment]
I'm closing the issue since there's no response. Please feel free to re-open if you still have the issue.
