### ISSUE TITLE
SNOW-404973: snowflake hook get_sqlalchemy_engine error in AWS MWAA

### ISSUE THREAD

**Issue by prabodh1194** [snowflakedb/snowflake-sqlalchemy#238]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
python 3.7

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
ubuntu 18.04

3. What are the component versions in the environment (`pip list`)? 
```
alembic==1.5.8
amqp==2.6.1
apache-airflow==2.0.2
apache-airflow-providers-amazon==1.4.0
apache-airflow-providers-celery==1.0.1
apache-airflow-providers-databricks==1.0.1
apache-airflow-providers-docker==1.2.0
apache-airflow-providers-ftp==1.0.1
apache-airflow-providers-http==1.1.1
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-oracle==1.1.0
apache-airflow-providers-postgres==1.0.2
apache-airflow-providers-presto==1.0.2
apache-airflow-providers-sftp==1.2.0
apache-airflow-providers-slack==3.0.0
apache-airflow-providers-snowflake==1.3.0
apache-airflow-providers-sqlite==1.0.2
apache-airflow-providers-ssh==1.3.0
apache-airflow-providers-tableau==1.0.0
apispec==3.3.2
argcomplete==1.12.3
asn1crypto==1.4.0
attrs==20.3.0
azure-common==1.1.27
azure-core==1.16.0
azure-storage-blob==12.8.1
Babel==2.9.0
bcrypt==3.2.0
billiard==3.6.4.0
blinker==1.4
boto3==1.17.53
botocore==1.20.53
cached-property==1.5.2
catboost==0.26
cattrs==1.5.0
celery==4.4.7
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
click==7.1.2
clickclick==20.10.2
colorama==0.4.4
colorlog==5.0.1
commonmark==0.9.1
connexion==2.7.0
croniter==0.3.37
cryptography==3.4.7
cx-Oracle==8.2.1
cycler==0.10.0
defusedxml==0.7.1
dill==0.3.2
dnspython==1.16.0
docker==3.7.3
docker-pycreds==0.4.0
docutils==0.16
email-validator==1.1.2
Flask==1.1.2
Flask-AppBuilder==3.3.0
Flask-Babel==1.0.0
Flask-Caching==1.10.1
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
flower==0.9.7
graphviz==0.16
gunicorn==19.10.0
humanize==3.4.1
idna==2.10
importlib-metadata==1.7.0
importlib-resources==1.5.0
inflection==0.5.1
iso8601==0.1.14
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.3
jmespath==0.10.0
jsonschema==3.2.0
kiwisolver==1.3.1
kombu==4.6.11
lazy-object-proxy==1.4.3
lockfile==0.12.2
Mako==1.1.4
Markdown==3.3.4
MarkupSafe==1.1.1
marshmallow==3.11.1
marshmallow-enum==1.5.1
marshmallow-oneofschema==2.1.0
marshmallow-sqlalchemy==0.23.1
matplotlib==3.4.2
msrest==0.6.21
natsort==7.1.1
numpy==1.20.2
oauthlib==3.1.1
openapi-schema-validator==0.1.5
openapi-spec-validator==0.3.0
oscrypto==1.2.1
pandas==1.2.4
paramiko==2.7.2
pendulum==2.1.2
Pillow==8.3.1
plotly==5.1.0
presto-python-client==0.7.0
prison==0.1.3
prometheus-client==0.8.0
psutil==5.8.0
psycopg2==2.8.6
psycopg2-binary==2.8.4
pycparser==2.20
pycryptodomex==3.10.1
pycurl==7.43.0.5
Pygments==2.8.1
PyJWT==1.7.1
PyNaCl==1.4.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.17.3
pysftp==0.2.9
python-daemon==2.3.0
python-dateutil==2.8.1
python-editor==1.0.4
python-nvd3==0.15.0
python-slugify==4.0.1
python3-openid==3.2.0
pytz==2021.1
pytzdata==2020.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rich==9.2.0
s3transfer==0.3.7
scipy==1.7.0
setproctitle==1.2.2
six==1.15.0
slack-sdk==3.6.0
snowflake-connector-python==2.5.0
snowflake-sqlalchemy==1.2.5
SQLAlchemy==1.3.24
SQLAlchemy-JSONField==1.0.0
SQLAlchemy-Utils==0.37.0
sshtunnel==0.1.5
statsd==3.3.0
swagger-ui-bundle==0.0.8
tableauserverclient==0.15.0
tabulate==0.8.9
tenacity==6.2.0
termcolor==1.1.0
text-unidecode==1.3
tornado==6.1
typing-extensions==3.7.4.3
unicodecsv==0.14.1
urllib3==1.25.11
vine==1.3.0
watchtower==1.0.1
websocket-client==1.0.1
Werkzeug==1.0.1
WTForms==2.3.3
zipp==3.4.1
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I have setup a snowflake hook using the airflow connection variable. Everything is working fine except for the `get_sqlalchemy_engine()`

5. What did you expect to see?
Expected to see an instance of sqlalchemy engine.

6. What did you see instead?
Error:

```
[2021-07-23 03:16:19,864] {{taskinstance.py:1482}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/scoring/score_delta_users.py", line 33, in run
    SNOWFLAKE_ENGINE = sqlalchemy.create_engine(conn_uri)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 525, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 260, in load
    return self.impls[name]()
  File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 283, in load
    mod = compat.import_(modulepath)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/sqlalchemy/__init__.py", line 25, in <module>
    from . import base, snowdialect
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/sqlalchemy/base.py", line 17, in <module>
    from .custom_commands import AWSBucket, AzureContainer, ExternalStage
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/sqlalchemy/custom_commands.py", line 14, in <module>
    from sqlalchemy.sql.roles import FromClauseRole
ModuleNotFoundError: No module named 'sqlalchemy.sql.roles'
```

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by prabodh1194** [comment]
i fixed this issue by ensuring that `snowflake-sqlalchemy` that is downloaded is v1.2.4 .
