### ISSUE TITLE
SNOW-664524: Error query builder of sqlalchemy - Boolean value of this clause is not defined

### ISSUE THREAD

**Issue by adrien-turiot-maxa** [snowflakedb/snowflake-sqlalchemy#344]
When querying using [the query API of `sqlalchemy`](https://docs.sqlalchemy.org/en/14/core/selectable.html), the execution raises this error: 

```
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT "COL1" FROM "MY_TABLE"': Boolean value of this clause is not defined
```

### Step to reproduce

- In Snowflake:
```sql
use my_database.my_schema;
create table my_table (col1 varchar, col2 varchar);
insert into my_table values ('a', 'b'), ('c', 'd');
```

- In a Python script:
```py
import pandas as pd
import snowflake.connector
from sqlalchemy import column, select, table
    
con = snowflake.connector.connect(
    account="<account>",
    user="<user>",
    authenticator="externalbrowser",
    database="TEST_DATABASE",
    schema="TEST_SCHEMA",
)

query = select(column("COL1")).select_from(table("MY_TABLE"))

print(pd.read_sql_query(query, con))
# ^ pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT "COL1" FROM "MY_TABLE"': Boolean value of this clause is not defined
```

<details>
<summary>Click here to see the logs (anonymized)</summary>

```log
2022-09-16 14:05:56,104 - MainThread connection.py:270 - __init__() - INFO - Snowflake Connector for Python Version: 2.7.12, Python Version: 3.8.10, Platform: macOS-12.6-x86_64-i386-64bit
2022-09-16 14:05:56,105 - MainThread connection.py:512 - connect() - DEBUG - connect
2022-09-16 14:05:56,105 - MainThread connection.py:802 - __config() - DEBUG - __config
2022-09-16 14:05:56,105 - MainThread connection.py:926 - __config() - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2022-09-16 14:05:56,105 - MainThread connection.py:944 - __config() - INFO - Setting use_openssl_only mode to False
2022-09-16 14:05:56,105 - MainThread converter.py:145 - __init__() - DEBUG - use_numpy: False
2022-09-16 14:05:56,105 - MainThread connection.py:705 - __open_connection() - DEBUG - REST API object was created: <account>.snowflakecomputing.com:443
2022-09-16 14:05:56,239 - MainThread auth.py:170 - authenticate() - DEBUG - authenticate
2022-09-16 14:05:56,239 - MainThread auth.py:200 - authenticate() - DEBUG - assertion content: ver:1-hint:105145105870858-ETMsDgAAAYNHeHlsABRBRVMvQ0JDL1BLQ1M1UGFkZGluZwEAABAAEAh3RN6VrfOZZ/ZA/lIzIfsAAACAfurBnx078VqbggxH1vwvvX0aAawCrm3AMKtY3v4zE/6G3wvJtFupwQXNL6jASY6FIx9DywqCblPjte44gjU+DCWrxrw3YhlT/TjaPI7CO+iz06OGOJFtqwD/5I3c0SDewT+e6j9UN1YexJwC6V5IcqvnWzcU8vRMdWgYzUxeDM0AFHQZxHB5BSey2ByxdEqA0AzfRMw1
2022-09-16 14:05:56,240 - MainThread auth.py:203 - authenticate() - DEBUG - account=<account>, user=<user>, database=TEST_DATABASE, schema=TEST_SCHEMA, warehouse=None, role=None, request_id=b5f96f0a-04b1-45b2-82fb-e8b3991043e9
2022-09-16 14:05:56,240 - MainThread auth.py:236 - authenticate() - DEBUG - body['data']: {'CLIENT_APP_ID': 'PythonConnector', 'CLIENT_APP_VERSION': '2.7.12', 'SVN_REVISION': None, 'ACCOUNT_NAME': '<account>', 'LOGIN_NAME': '<user>', 'CLIENT_ENVIRONMENT': {'APPLICATION': 'PythonConnector', 'OS': 'Darwin', 'OS_VERSION': 'macOS-12.6-x86_64-i386-64bit', 'PYTHON_VERSION': '3.8.10', 'PYTHON_RUNTIME': 'CPython', 'PYTHON_COMPILER': 'Clang 12.0.5 (clang-1205.0.22.9)', 'OCSP_MODE': 'FAIL_OPEN', 'TRACING': 10, 'LOGIN_TIMEOUT': 120, 'NETWORK_TIMEOUT': None}, 'AUTHENTICATOR': 'ID_TOKEN', 'TOKEN': '<token>', 'SESSION_PARAMETERS': {'CLIENT_PREFETCH_THREADS': 4, 'CLIENT_STORE_TEMPORARY_CREDENTIAL': True}}
2022-09-16 14:05:56,240 - MainThread auth.py:254 - authenticate() - DEBUG - Timeout set to 120
2022-09-16 14:05:56,240 - MainThread retry.py:351 - from_int() - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2022-09-16 14:05:56,240 - MainThread network.py:1147 - _use_requests_session() - DEBUG - Session status for SessionPool '<account>.snowflakecomputing.com', SessionPool 1/1 active sessions
2022-09-16 14:05:56,240 - MainThread network.py:827 - _request_exec_wrapper() - DEBUG - remaining request timeout: 120, retry cnt: 1
2022-09-16 14:05:56,240 - MainThread network.py:808 - add_request_guid() - DEBUG - Request guid: 74046e22-e103-4e7e-a874-859e84787111
2022-09-16 14:05:56,240 - MainThread network.py:1006 - _request_exec() - DEBUG - socket timeout: 60
2022-09-16 14:05:56,370 - MainThread connectionpool.py:1003 - _new_conn() - DEBUG - Starting new HTTPS connection (1): <account>.snowflakecomputing.com:443
2022-09-16 14:05:56,515 - MainThread cache.py:490 - _save() - DEBUG - acquiring /Users/me/Library/Caches/Snowflake/ocsp_cache.lock timed out, skipping saving...
2022-09-16 14:05:56,517 - MainThread ocsp_snowflake.py:507 - reset_cache_dir() - DEBUG - cache directory: /Users/me/Library/Caches/Snowflake
2022-09-16 14:05:56,629 - MainThread ssl_wrap_socket.py:80 - ssl_wrap_socket_with_ocsp() - DEBUG - OCSP Mode: FAIL_OPEN, OCSP response cache file name: None
2022-09-16 14:05:56,629 - MainThread ocsp_snowflake.py:549 - reset_ocsp_response_cache_uri() - DEBUG - ocsp_response_cache_uri: file:///Users/me/Library/Caches/Snowflake/ocsp_response_cache.json
2022-09-16 14:05:56,629 - MainThread ocsp_snowflake.py:550 - reset_ocsp_response_cache_uri() - DEBUG - OCSP_VALIDATION_CACHE size: 0
2022-09-16 14:05:56,629 - MainThread ocsp_snowflake.py:332 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP response cache server is enabled: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json
2022-09-16 14:05:56,629 - MainThread ocsp_snowflake.py:368 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP dynamic cache server RETRY URL: None
2022-09-16 14:05:56,632 - MainThread ocsp_asn1crypto.py:238 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-09-15 19:41:06+00:00
2022-09-16 14:05:56,697 - MainThread ocsp_snowflake.py:585 - read_ocsp_response_cache_file() - DEBUG - Read OCSP response cache file: /Users/me/Library/Caches/Snowflake/ocsp_response_cache.json, count=183
2022-09-16 14:05:56,697 - MainThread ocsp_snowflake.py:1118 - validate() - DEBUG - validating certificate: <account>.snowflakecomputing.com
2022-09-16 14:05:56,697 - MainThread ocsp_asn1crypto.py:439 - extract_certificate_chain() - DEBUG - # of certificates: 3
2022-09-16 14:05:56,698 - MainThread ocsp_asn1crypto.py:444 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('state_or_province_name', 'California'), ('locality_name', 'San Mateo'), ('organization_name', 'Snowflake Inc.'), ('common_name', '*.us-central1.gcp.snowflakecomputing.com')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'DigiCert Inc'), ('common_name', 'DigiCert TLS RSA SHA256 2020 CA1')])
2022-09-16 14:05:56,698 - MainThread ocsp_asn1crypto.py:444 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('organization_name', 'DigiCert Inc'), ('common_name', 'DigiCert TLS RSA SHA256 2020 CA1')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'DigiCert Inc'), ('organizational_unit_name', 'www.digicert.com'), ('common_name', 'DigiCert Global Root CA')])
2022-09-16 14:05:56,699 - MainThread ocsp_asn1crypto.py:444 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('organization_name', 'DigiCert Inc'), ('organizational_unit_name', 'www.digicert.com'), ('common_name', 'DigiCert Global Root CA')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'DigiCert Inc'), ('organizational_unit_name', 'www.digicert.com'), ('common_name', 'DigiCert Global Root CA')])
2022-09-16 14:05:56,701 - MainThread ocsp_snowflake.py:725 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('country_name', 'US'), ('state_or_province_name', 'California'), ('locality_name', 'San Mateo'), ('organization_name', 'Snowflake Inc.'), ('common_name', '*.us-central1.gcp.snowflakecomputing.com')])
2022-09-16 14:05:56,702 - MainThread ocsp_snowflake.py:725 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('country_name', 'US'), ('organization_name', 'DigiCert Inc'), ('common_name', 'DigiCert TLS RSA SHA256 2020 CA1')])
2022-09-16 14:05:56,703 - MainThread ocsp_snowflake.py:647 - write_ocsp_response_cache_file() - DEBUG - writing OCSP response cache file to /Users/me/Library/Caches/Snowflake/ocsp_response_cache.json
2022-09-16 14:05:56,703 - MainThread ocsp_snowflake.py:1794 - encode_ocsp_response_cache() - DEBUG - encoding OCSP response cache to JSON
2022-09-16 14:05:56,724 - MainThread ocsp_snowflake.py:1175 - _validate() - DEBUG - ok
2022-09-16 14:05:56,868 - MainThread connectionpool.py:456 - _make_request() - DEBUG - https://<account>.snowflakecomputing.com:443 "POST /session/v1/login-request?request_id=b5f96f0a-04b1-45b2-82fb-e8b3991043e9&databaseName=TEST_DATABASE&schemaName=TEST_SCHEMA&request_guid=74046e22-e103-4e7e-a874-859e84787111 HTTP/1.1" 200 None
2022-09-16 14:05:56,869 - MainThread network.py:1032 - _request_exec() - DEBUG - SUCCESS
2022-09-16 14:05:56,869 - MainThread network.py:1152 - _use_requests_session() - DEBUG - Session status for SessionPool '<account>.snowflakecomputing.com', SessionPool 0/1 active sessions
2022-09-16 14:05:56,869 - MainThread network.py:715 - _post_request() - DEBUG - ret[code] = None, after post request
2022-09-16 14:05:56,869 - MainThread auth.py:373 - authenticate() - DEBUG - completed authentication
2022-09-16 14:05:56,869 - MainThread auth.py:416 - authenticate() - DEBUG - token = ******
2022-09-16 14:05:56,869 - MainThread auth.py:419 - authenticate() - DEBUG - master_token = ******
2022-09-16 14:05:56,869 - MainThread auth.py:423 - authenticate() - DEBUG - id_token = NULL
2022-09-16 14:05:56,869 - MainThread auth.py:427 - authenticate() - DEBUG - mfa_token = NULL
2022-09-16 14:05:56,869 - MainThread auth.py:497 - _write_temporary_credential() - DEBUG - no credential is given when try to store temporary credential
venv/pandas/io/sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
2022-09-16 14:05:56,873 - MainThread connection.py:624 - cursor() - DEBUG - cursor
2022-09-16 14:05:56,873 - MainThread cursor.py:630 - execute() - DEBUG - executing SQL/command
2022-09-16 14:05:56,873 - MainThread connection.py:624 - cursor() - DEBUG - cursor
2022-09-16 14:05:56,873 - MainThread cursor.py:630 - execute() - DEBUG - executing SQL/command
2022-09-16 14:05:56,873 - MainThread cursor.py:669 - execute() - DEBUG - binding: [ROLLBACK] with input=[None], processed=[{}]
2022-09-16 14:05:56,873 - MainThread cursor.py:715 - execute() - INFO - query: [ROLLBACK]
2022-09-16 14:05:56,874 - MainThread connection.py:1302 - _next_sequence_counter() - DEBUG - sequence counter: 1
2022-09-16 14:05:56,874 - MainThread cursor.py:460 - _execute_helper() - DEBUG - Request id: 898b37cb-095d-4afd-bcc7-9bf07e7b5211
2022-09-16 14:05:56,874 - MainThread cursor.py:462 - _execute_helper() - DEBUG - running query [ROLLBACK]
2022-09-16 14:05:56,874 - MainThread cursor.py:471 - _execute_helper() - DEBUG - is_file_transfer: False
2022-09-16 14:05:56,874 - MainThread connection.py:972 - cmd_query() - DEBUG - _cmd_query
2022-09-16 14:05:56,874 - MainThread connection.py:995 - cmd_query() - DEBUG - sql=[ROLLBACK], sequence_id=[1], is_file_transfer=[False]
2022-09-16 14:05:56,874 - MainThread network.py:1147 - _use_requests_session() - DEBUG - Session status for SessionPool '<account>.snowflakecomputing.com', SessionPool 1/1 active sessions
2022-09-16 14:05:56,874 - MainThread network.py:827 - _request_exec_wrapper() - DEBUG - remaining request timeout: None, retry cnt: 1
2022-09-16 14:05:56,874 - MainThread network.py:808 - add_request_guid() - DEBUG - Request guid: 033aa196-8c37-4cbb-9d6b-c94bd8f654ac
2022-09-16 14:05:56,874 - MainThread network.py:1006 - _request_exec() - DEBUG - socket timeout: 60
2022-09-16 14:05:57,017 - MainThread connectionpool.py:456 - _make_request() - DEBUG - https://<account>.snowflakecomputing.com:443 "POST /queries/v1/query-request?requestId=898b37cb-095d-4afd-bcc7-9bf07e7b5211&request_guid=033aa196-8c37-4cbb-9d6b-c94bd8f654ac HTTP/1.1" 200 None
2022-09-16 14:05:57,018 - MainThread network.py:1032 - _request_exec() - DEBUG - SUCCESS
2022-09-16 14:05:57,018 - MainThread network.py:1152 - _use_requests_session() - DEBUG - Session status for SessionPool '<account>.snowflakecomputing.com', SessionPool 0/1 active sessions
2022-09-16 14:05:57,018 - MainThread network.py:715 - _post_request() - DEBUG - ret[code] = None, after post request
2022-09-16 14:05:57,018 - MainThread network.py:739 - _post_request() - DEBUG - Query id: 01a7031d-0000-b402-0000-5fa10de4918a
2022-09-16 14:05:57,019 - MainThread cursor.py:737 - execute() - DEBUG - sfqid: 01a7031d-0000-b402-0000-5fa10de4918a
2022-09-16 14:05:57,019 - MainThread cursor.py:739 - execute() - INFO - query execution done
2022-09-16 14:05:57,019 - MainThread cursor.py:741 - execute() - DEBUG - SUCCESS
2022-09-16 14:05:57,019 - MainThread cursor.py:744 - execute() - DEBUG - PUT OR GET: None
2022-09-16 14:05:57,019 - MainThread cursor.py:841 - _init_result_and_meta() - DEBUG - Query result format: json
2022-09-16 14:05:57,019 - MainThread result_batch.py:440 - _parse() - DEBUG - parsing for result batch id: 1
Traceback (most recent call last):
  File "venv/pandas/io/sql.py", line 2023, in execute
    cur.execute(*args, **kwargs)
  File "venv/snowflake/connector/cursor.py", line 641, in execute
    command = command.strip(" \t\n\r") if command else None
  File "venv/sqlalchemy/sql/elements.py", line 590, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 30, in <module>
    pd.read_sql_query(query, con)
  File "venv/pandas/io/sql.py", line 400, in read_sql_query
    return pandas_sql.read_query(
  File "venv/pandas/io/sql.py", line 2083, in read_query
    cursor = self.execute(*args)
  File "venv/pandas/io/sql.py", line 2035, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT "COL1" 
FROM "MY_TABLE"': Boolean value of this clause is not defined
```

</details>

<details>
<summary>In comparison, this works fine in SQLite here:</summary>

```py
import pandas as pd
from sqlalchemy import create_engine, column, select, table

con = create_engine("sqlite://").connect()
con.execute("create table my_table (col1 varchar, col2 varchar)")
con.execute("insert into my_table values ('a', 'b'), ('c', 'd')")

query = select(column("COL1")).select_from(table("MY_TABLE"))
print(pd.read_sql_query(query, con))  # works fine
```

</details>

Environment info:
```
System: macOS-12.6-x86_64-i386-64bit
python 3.8.10

snowflake-connector-python==2.7.12
snowflake-sqlalchemy==1.4.1
```

**Comment by jonwiggins** [comment]
I had this same issue.

The error message is confusing, but the underlying problem is that pandas needs a sqlalchemy connector to snowflake, rather than a snowflake connector.

So you want to do
```python
def get_con():
    return con = snowflake.connector.connect(
        account="<account>",
        user="<user>",
        authenticator="externalbrowser",
        database="TEST_DATABASE",
        schema="TEST_SCHEMA",
    )

sa_conn = sa.create_engine(..., creator=get_con,)
query = select(column("COL1")).select_from(table("MY_TABLE"))

print(pd.read_sql_query(query, sa_conn))
```
