### ISSUE TITLE
Snowflake connection not closing after execution

### ISSUE THREAD

**Issue by ulti-star** [snowflakedb/snowflake-sqlalchemy#37]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.6

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Linux-4.9.60-linuxkit-aufs-x86_64-with-debian-8.10

3. What are the component versions in the environment (`pip list`)? 

asn1crypto (0.24.0)
azure-common (1.1.8)
azure-nspkg (2.0.0)
azure-storage (0.34.2)
boto3 (1.4.8)
botocore (1.8.36)
certifi (2018.1.18)
cffi (1.11.4)
cryptography (2.1.4)
docutils (0.14)
future (0.16.0)
idna (2.6)
ijson (2.3)
jmespath (0.9.3)
pexpect (4.2.1)
pip (9.0.1)
profilehooks (1.8.1)
psycopg2 (2.6.2)
ptyprocess (0.5.2)
pyasn1 (0.3.7)
pyasn1-modules (0.1.5)
pycparser (2.18)
pycryptodome (3.4.8)
PyMySQL (0.6.7)
pyOpenSSL (17.5.0)
python-dateutil (2.6.1)
pytz (2017.3)
requests (2.11.1)
s3transfer (0.1.12)
setuptools (38.2.4)
six (1.11.0)
snowflake-connector-python (1.4.13)
snowflake-sqlalchemy (1.0.7)
SQLAlchemy (1.1.15)
tqdm (4.4.0)
websocket-client (0.37.0)
wheel (0.30.0)

4. What did you do?
I posted this issue in StackOverflow and am creating this issue in GitHub as the problem was not resolved.

https://stackoverflow.com/questions/48464343/sqlalchemy-snowflake-not-closing-connection-after-successfully-retrieving-result

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```import logging
from sqlalchemy import create_engine
from snowflake.sqlalchemy import URL

for logger_name in ['snowflake', 'botocore']:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.FileHandler('log')
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)

engine = create_engine(URL(
            account=xxxxx,
            user=xxxxxx,
            password=xxxxxxx,
            database=xxxxx,
            schema=xxxxx,
            warehouse=xxxxxx))

query = """SELECT * FROM db_name.schema_name.table_name LIMIT 200000"""

print ("creating connection object")
connection = engine.connect()

print ("executing query")
results = engine.execute(query)

print ("Total rows retreived by the query")
print(results.rowcount)

print ("closing connection")
connection.close()

print ("disposing engine")
engine.dispose()```

5. What did you expect to see?
I expect the program to print the number of rows and exit.

6. What did you see instead?
The connection just hangs in there until I manually kill the python process. But after adding the logging function the program started throwing errors which I have added below.

7. Can you set logging to DEBUG and collect the logs?

creating connection object
executing query
Total rows retreived by the query
109323
closing connection
disposing engine

Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/connection.py", line 375, in rollback
    self.cursor().execute("ROLLBACK")
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 479, in execute
    _is_put_get=_is_put_get)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 368, in _execute_helper
    _no_results=_no_results)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/connection.py", line 617, in cmd_query
    data, client=client, _no_results=_no_results)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 248, in request
    timeout=self._connection.network_timeout)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 387, in _post_request
    no_retry=no_retry, socket_timeout=socket_timeout)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 454, in fetch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 517, in _request_exec_wrapper
    raise e
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 480, in _request_exec_wrapper
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 633, in _request_exec
    auth=SnowflakeAuth(token),
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 224, in connect
    is_time_off = datetime.date.today() < RECENT_DATE
ModuleNotFoundError: import of time halted; None in sys.modules

**Comment by smtakeda** [comment]
can you change
```
results = engine.execute(query)
```
to
```
results = connection.execute(query)
```
?

**Comment by ulti-star** [comment]
Ohh.. thats seems to have fixed the problem. Thank you.

Sorry for bothering you so much.

**Comment by smtakeda** [comment]
No problem. Feel free to post questions here.
