### ISSUE TITLE
Error for Missing Table Inconsistent with Other Dialects

### ISSUE THREAD

**Issue by davidov541** [snowflakedb/snowflake-sqlalchemy#374]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?
```
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
```
2. What operating system and processor architecture are you using?
```
[GCC 9.4.0]
Linux-4.14.301-224.520.amzn2.x86_64-x86_64-with-glibc2.29
```
3. What are the component versions in the environment (`pip freeze`)?
```
...
snowflake-connector-python==2.9.0
snowflake-sqlalchemy==1.4.4
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.46
...
```
4. What did you do?

Run the following script.
```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.asymmetric import dsa
from cryptography.hazmat.primitives import serialization
import logging
import sys
from sqlalchemy import Table, Column, Integer, String, MetaData
from sqlalchemy import create_engine
from snowflake.sqlalchemy import URL

encrypted_key_path = sys.argv[1]
encrypted_key_password = sys.argv[2]

with open(encrypted_key_path, "rb") as key:
    p_key = serialization.load_pem_private_key(
        key.read(),
        password=encrypted_key_password.encode(),
        backend=default_backend()
    )

pkb = p_key.private_bytes(
    encoding=serialization.Encoding.DER,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption())

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector']:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)


engine = create_engine(URL(
        account = '...',
        user = '...',
        database = '...',
        schema = '...',
        warehouse = '...',
        role='...',
    ),
    connect_args={
        'private_key': pkb,
    },
)
metadata_obj = MetaData()
user_table = Table("does_not_exist",
                   metadata_obj,
                   Column("id", Integer, primary_key=True),
                   Column("name", String(30)),
                   Column("fullname", String),
                   autoload_with=engine)
engine.dispose()
```

5. What did you expect to see?

Standard SQLAlchemy scripts return a NoSuchTableError exception when a table that doesn't exist is pulled from the engine. Instead we see a KeyNotFound error.

6. Can you set logging to DEBUG and collect the logs?

Full logs were too long for description. Including relevant portion below.

```
2023-01-26 17:26:03,219 - ThreadPoolExecutor-3_0 result_batch.py:305 - _download() - DEBUG - successfully downloaded result batch id: data_0_0_1
2023-01-26 17:26:03,219 - ThreadPoolExecutor-3_0 result_batch.py:635 - _create_iter() - DEBUG - started loading result batch id: data_0_0_1
2023-01-26 17:26:03,219 - ThreadPoolExecutor-3_0 arrow_iterator.cpython-38-x86_64-linux-gnu.so:0 - __cinit__() - DEBUG - Batches read: 3
2023-01-26 17:26:03,219 - ThreadPoolExecutor-3_0 result_batch.py:638 - _create_iter() - DEBUG - finished loading result batch id: data_0_0_1
2023-01-26 17:26:03,219 - MainThread result_set.py:87 - result_set_iterator() - DEBUG - user began consuming result batch 1
2023-01-26 17:26:03,220 - MainThread CArrowIterator.cpp:16 - CArrowIterator() - DEBUG - Arrow BatchSize: 3
2023-01-26 17:26:03,220 - MainThread CArrowChunkIterator.cpp:50 - CArrowChunkIterator() - DEBUG - Arrow chunk info: batchCount 3, columnCount 12, use_numpy: 0
2023-01-26 17:26:03,220 - MainThread CArrowChunkIterator.cpp:74 - next() - DEBUG - Current batch index: 0, rows in current batch: 104
2023-01-26 17:26:03,221 - MainThread CArrowChunkIterator.cpp:74 - next() - DEBUG - Current batch index: 1, rows in current batch: 97
2023-01-26 17:26:03,222 - MainThread CArrowChunkIterator.cpp:74 - next() - DEBUG - Current batch index: 2, rows in current batch: 104
2023-01-26 17:26:03,224 - MainThread result_set.py:89 - result_set_iterator() - DEBUG - user finished consuming result batch 1
2023-01-26 17:26:03,224 - MainThread connection.py:648 - cursor() - DEBUG - cursor
2023-01-26 17:26:03,224 - MainThread cursor.py:662 - execute() - DEBUG - executing SQL/command
2023-01-26 17:26:03,225 - MainThread cursor.py:582 - _preprocess_pyformat_query() - DEBUG - binding: [ROLLBACK] with input=[None], processed=[{}]
2023-01-26 17:26:03,225 - MainThread cursor.py:727 - execute() - INFO - query: [ROLLBACK]
2023-01-26 17:26:03,225 - MainThread connection.py:1334 - _next_sequence_counter() - DEBUG - sequence counter: 7
2023-01-26 17:26:03,225 - MainThread cursor.py:457 - _execute_helper() - DEBUG - Request id: cfd14772-7292-4c76-a95d-4d09e23bb998
2023-01-26 17:26:03,225 - MainThread cursor.py:459 - _execute_helper() - DEBUG - running query [ROLLBACK]
2023-01-26 17:26:03,225 - MainThread cursor.py:466 - _execute_helper() - DEBUG - is_file_transfer: True
2023-01-26 17:26:03,225 - MainThread connection.py:1011 - cmd_query() - DEBUG - _cmd_query
2023-01-26 17:26:03,225 - MainThread connection.py:1034 - cmd_query() - DEBUG - sql=[ROLLBACK], sequence_id=[7], is_file_transfer=[False]
2023-01-26 17:26:03,225 - MainThread network.py:1155 - _use_requests_session() - DEBUG - Session status for SessionPool '<account_number>.snowflakecomputing.com', SessionPool 1/1 active sessions
2023-01-26 17:26:03,225 - MainThread network.py:835 - _request_exec_wrapper() - DEBUG - remaining request timeout: None, retry cnt: 1
2023-01-26 17:26:03,225 - MainThread network.py:816 - add_request_guid() - DEBUG - Request guid: 2a4af6dd-3c94-41d0-a914-23b040aa9d14
2023-01-26 17:26:03,225 - MainThread network.py:1014 - _request_exec() - DEBUG - socket timeout: 60
2023-01-26 17:26:03,287 - MainThread connectionpool.py:456 - _make_request() - DEBUG - https://<account_number>.snowflakecomputing.com:443 "POST /queries/v1/query-request?requestId=cfd14772-7292-4c76-a95d-4d09e23bb998&request_guid=2a4af6dd-3c94-41d0-a914-23b040aa9d14 HTTP/1.1" 200 1102
2023-01-26 17:26:03,288 - MainThread network.py:1040 - _request_exec() - DEBUG - SUCCESS
2023-01-26 17:26:03,288 - MainThread network.py:1160 - _use_requests_session() - DEBUG - Session status for SessionPool '<account_number>.snowflakecomputing.com', SessionPool 0/1 active sessions
2023-01-26 17:26:03,288 - MainThread network.py:715 - _post_request() - DEBUG - ret[code] = None, after post request
2023-01-26 17:26:03,288 - MainThread network.py:739 - _post_request() - DEBUG - Query id: 01a9e976-0602-f298-0070-9e0300f1ecca
2023-01-26 17:26:03,288 - MainThread cursor.py:734 - execute() - DEBUG - sfqid: 01a9e976-0602-f298-0070-9e0300f1ecca
2023-01-26 17:26:03,288 - MainThread cursor.py:740 - execute() - INFO - query execution done
2023-01-26 17:26:03,289 - MainThread cursor.py:754 - execute() - DEBUG - SUCCESS
2023-01-26 17:26:03,289 - MainThread cursor.py:773 - execute() - DEBUG - PUT OR GET: False
2023-01-26 17:26:03,289 - MainThread cursor.py:864 - _init_result_and_meta() - DEBUG - Query result format: json
2023-01-26 17:26:03,289 - MainThread result_batch.py:440 - _parse() - DEBUG - parsing for result batch id: 1
2023-01-26 17:26:03,289 - MainThread cursor.py:878 - _init_result_and_meta() - INFO - Number of results in first chunk: 1
Traceback (most recent call last):
  File "./src/dq/error_reproduction.py", line 48, in <module>
    user_table = Table("does_not_exist",
  File "<string>", line 2, in __new__
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "/usr/local/lib/python3.8/dist-packages/snowflake/sqlalchemy/snowdialect.py", line 672, in get_columns
    return schema_columns[self.normalize_name(table_name)]
KeyError: 'does_not_exist'
```

**Comment by davidov541** [comment]
I'm planning to create a PR to fix this, I've identified the issue is in snowdialect.py:672, just going to add a check if the key is in the list of tables, and if not, then return the correct exception.

**Comment by davidov541** [comment]
PR for this is now available here: https://github.com/snowflakedb/snowflake-sqlalchemy/pull/375
