### ISSUE TITLE
botocore requirement limitation

### ISSUE THREAD

**Issue by jorgebaez212** [snowflakedb/snowflake-sqlalchemy#41]
It is quite common to use awscli, especially if sync between buckets is needed, but if you install the latest version of awscli, botocore version is upgraded to botocore 1.8.42, and when trying to query snowflake using sqlalchemy, the following error rises:
```
File "/some/test/virtualenv/path/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine 
    return strategy.create(*args, **kwargs) 
File "/some/test/virtualenv/path/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 56, in create 
    entrypoint = u._get_entrypoint() 
File "/some/test/virtualenv/path/python2.7/site-packages/sqlalchemy/engine/url.py", line 139, in _get_entrypoint 
    cls = registry.load(name) 
File "/some/test/virtualenv/path/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 214, in load
    return impl.load() 
File "/some/test/virtualenv/path/python2.7/dist-packages/pkg_resources.py", line 2188, in load 
    self.require(env, installer)
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2202, in require
    items = working_set.resolve(reqs, env, installer)
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (botocore 1.8.38 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('botocore>=1.7.0,<1.8.0'))
```
Is it really necessary to set an upper limit for bocore versions to 1.8.0?
Could it be possible to allow the usage of the latest botocore version?

**Comment by smtakeda** [comment]
That latest version 1.5.0 already bumped up the upper limit to 1.9.0:
https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L40

Can you update the driver to the latest one?

The reason it limits is because the connection uses botocore's request package with OCSP check:
https://github.com/boto/botocore/tree/develop/botocore/vendored/requests

I'm afraid the change of botocore could break compatibility, though they don't strictly follow semantic versioning.

We came across a compatibility issue with other package, so we are a bit cautious.

**Comment by jorgebaez212** [comment]
In this case, the error occurs when trying to use sqlalchemy.create_engine.

Snowflake libraries are up to date on these environments, and the upgrade of boto that occurs when installing awscli can be seen using pip freeze.

#This env does not work:
```
(testenv) user@server123:~$ pip freeze | grep aws
awscli==1.14.38
(testenv) user@server123:~$ pip freeze | grep snowf
snowflake-connector-python==1.5.0
snowflake-sqlalchemy==1.1.0
(testenv) user@server123:~$ pip freeze | grep boto
boto==2.48.0
boto3==1.4.7
botocore==1.8.42
```
#This env works with no problems
```
(py279) user@server123:~$ pip freeze | grep aws
(py279) user@server123:~$ pip freeze | grep snowf
snowflake-connector-python==1.5.0
snowflake-sqlalchemy==1.1.0
(py279) user@server123:~$ pip freeze | grep boto
boto==2.48.0
boto3==1.4.7
botocore==1.7.48
```
I thought the problem was related to this sqlalchemy module, but do you think it could be something else?

**Comment by smtakeda** [comment]
I think it is due to `boto3` limiting the version of `botocore`:

https://github.com/boto/boto3/commit/9d5fac2a36a31b9665a8d80c7dfe8df9fac4ceb3
```
-    botocore>=1.6.0,<1.7.0
+    botocore>=1.7.0,<1.8.0
```
This case worked in Python 3.6.2 on Mac:
```
>pip freeze | grep -E "(snowflake|aws|boto)"
awscli==1.14.38
boto==2.48.0
boto3==1.5.28
botocore==1.8.42
snowflake-connector-python==1.5.0
snowflake-sqlalchemy==1.1.0
>more connect.py
from sqlalchemy import create_engine
engine = create_engine("snowflake://... (connection string) ...")
for rec in engine.execute("select 1"):
    print(rec)
>python connect.py
(1,)
```

But downgrading boto3 to 1.4.7 raises an error:
```
>pip freeze | grep -E "(snowflake|aws|boto)"
awscli==1.14.38
boto==2.48.0
boto3==1.4.7
botocore==1.8.42
snowflake-connector-python==1.5.0
snowflake-sqlalchemy==1.1.0
>python connect.py
Traceback (most recent call last):
  File "connect.py", line 3, in <module>
    engine = create_engine("snowflake://snowman:test@snowflake.reg.local:8082/?database=testdb&schema=testschema&warehouse=regress&role=sysadmin&protocol=http&account=testaccount")
  File "/tmp/b/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "/tmp/b/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 56, in create
    entrypoint = u._get_entrypoint()
  File "/tmp/b/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 150, in _get_entrypoint
    cls = registry.load(name)
  File "/tmp/b/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 217, in load
    return impl.load()
  File "/tmp/b/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2407, in load
    self.require(*args, **kwargs)
  File "/tmp/b/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2430, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/tmp/b/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.8.42 (/private/tmp/b/lib/python3.6/site-packages), Requirement.parse('botocore<1.8.0,>=1.7.0'), {'boto3'})
```

**Comment by jorgebaez212** [comment]
Thanks! upgrading boto3 to 1.5.28 solved this connection problem.
