### ISSUE TITLE
pkg_resources.ContextualVersionConflict: (python-dateutil 2.7.0 (/tmp/g/lib/python3.4/site-packages), Requirement.parse('python-dateutil<2.7.0,>=2.1'), {'botocore'})

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/snowflake-sqlalchemy#42]
https://github.com/boto/botocore 1.9.8 tighten the upper bound of https://github.com/dateutil/dateutil/ version to `<2.7.0`. If you install snowflake-sqlalchemy in a fresh virtualenv and attempt to make a connection, you'll get this:

```
Traceback (most recent call last):
  File "/home/stakeda/test_python/sqlalchemy_test.py", line 31, in <module>
    poolclass=QueuePool)
  File "/tmp/g/lib/python3.4/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/tmp/g/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 57, in create
    entrypoint = u._get_entrypoint()
  File "/tmp/g/lib/python3.4/site-packages/sqlalchemy/engine/url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "/tmp/g/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 217, in load
    return impl.load()
  File "/tmp/g/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2309, in load
    self.require(*args, **kwargs)
  File "/tmp/g/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2326, in require
    items = working_set.resolve(reqs, env, installer)
  File "/tmp/g/lib/python3.4/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.7.0 (/tmp/g/lib/python3.4/site-packages), Requirement.parse('python-dateutil<2.7.0,>=2.1'), {'botocore'})
```
The workaround is this:
```
pip install -U python-dateutil==2.6.1
```

**Comment by smtakeda** [comment]
not reproducible in the latest versions.
