### ISSUE TITLE
Long values in params mishandled

### ISSUE THREAD

**Issue by darrint** [snowflakedb/snowflake-sqlalchemy#54]
`ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001003 (42000): SQL compilation error:
syntax error line 3 at position 14 unexpected 'L'.`

It appears to me that long values are being mishandled. I don't know whether to blame snowflake-sqlalchemy for trying to substitute them as strings or the connector for substituting as strings incorrectly. I think it's the latter. (Or I'm doing it all wrong.)  

I've included a full working program to reproduce. I think the problem is here is shown in the log, but I don't know what I should do about it.

DEBUG:snowflake.connector.cursor:parameters: {u'param_1': u'10', **u'buid_1': u'1L'**}

The `L` on the `long(1)` is being sent as a literal to snowflake which is rejecting it.

1. What version of Python are you using (`python --version`)?

2.7.12 (default, Dec  4 2017, 14:50:18) \n[GCC 5.4.0 20160609]

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Linux-4.4.0-122-generic-x86_64-with-Ubuntu-16.04-xenial

3. What are the component versions in the environment (`pip list`)? 

```

alabaster (0.7.9)
alembic (0.9.9)
amqp (1.4.9)
aniso8601 (3.0.0)
anyjson (0.3.3)
asn1crypto (0.24.0)
astroid (1.4.8)
AuthorizeSauce (0.5.0)
aws-requests-auth (0.4.1)
azure-common (1.1.11)
azure-nspkg (2.0.0)
azure-storage (0.36.0)
Babel (2.3.4)
backports.functools-lru-cache (1.3)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.1.3)
bidict (0.3.1)
billiard (3.3.0.23)
bleach (1.4)
boto (2.25.0)
boto3 (1.7.33)
botocore (1.10.33)
celery (3.1.24)
certifi (2018.4.16)
cffi (1.11.5)
colorama (0.2.5)
configparser (3.5.0)
construct (2.8.7)
coverage (4.2)
cryptography (2.2.2)
cssselect (0.9.1)
cssutils (1.0.1)
ddtrace (0.10.1)
decorator (3.4.0)
defusedxml (0.4.1)
Django (1.9.10)
django-ajax-selects (1.5.1)
django-appconf (1.0.2)
django-celery (3.1.17)
django-composite-foreignkey (1.0.0a10)
django-compressor (2.1)
django-cors-headers (1.1.0)
django-cprofile-middleware (0.4)
django-debug-toolbar (1.6)
django-el-pagination (3.0.1)
django-extensions (1.7.4)
django-filter (1.0.4)
django-fsm-widget (0.0.3)
django-haystack (2.5.0)
django-impersonate (1.0.1)
django-jenkins (0.110.0)
django-jsonfield (1.0.1)
django-jsonfield-compat (0.4.4)
django-memcached (0.1.2)
django-messages (0.5.0rc0)
django-nose (1.4.4)
django-passwords (0.2.0)
django-polymorphic (1.3)
django-recaptcha (1.3.0)
django-remote-forms (0.0.1)
django-storages (1.1.4)
django-taggit (0.21.3)
django-tastypie (0.13.3)
django-waffle (0.12.0)
django-webpack-loader (0.6.0)
django-widget-tweaks (1.1.2)
djangorestframework (3.6.3)
dnspython (1.15.0)
docutils (0.12)
elasticsearch (5.3.0)
email-validator (1.0.2)
enum34 (1.1.6)
factory-boy (2.8.1)
Faker (0.8.3)
freezegun (0.3.7)
future (0.15.2)
futures (3.1.1)
geoip2 (2.4.2)
graphene (2.1.1)
graphene-django (2.0.0)
graphql-core (2.0)
graphql-relay (0.4.5)
html5lib (0.999)
httplib2 (0.10.3)
idna (2.6)
ijson (2.3)
ipaddress (1.0.18)
ipdb (0.8)
ipython (1.2.1)
iso8601 (0.1.12)
isort (4.2.5)
Jinja2 (2.8)
jira (0.42)
jmespath (0.9.3)
kombu (3.0.37)
lazy-object-proxy (1.2.2)
loremipsum (1.0.5)
lxml (3.2.4)
Mako (1.0.7)
Markdown (2.4)
markdown2 (2.1.0)
MarkupSafe (0.23)
maxminddb (1.3.0)
mccabe (0.5.2)
mimeparse (0.1.3)
mock (1.0.1)
msgpack-python (0.5.6)
MySQL-python (1.2.5)
newrelic (2.50.0.39)
nose (1.3.7)
oauth2client (4.0.0)
oauthlib (2.0.0)
ordereddict (1.1)
pefile (2016.3.28)
pep8 (1.3.3)
pexpect (3.1)
pip (8.1.1)
promise (2.1)
psycopg2 (2.7.4)
ptyprocess (0.5)
pyasn1 (0.2.3)
pyasn1-modules (0.0.9)
pycparser (2.18)
pycryptodome (3.6.1)
pydns (2.3.6)
pyflakes (0.5.0)
Pygments (2.1.3)
PyJWT (1.6.4)
pylint (1.6.4)
pymongo (3.2.2)
pymongo-env (0.0.3)
pynliner (0.5.1)
pyOpenSSL (17.5.0)
pysolr (3.2.0)
python-dateutil (2.5.3)
python-editor (1.0.3)
python-memcached (1.53)
python-mimeparse (1.6.0)
python-ptrace (0.9.1)
pytz (2016.7)
PyYAML (3.10)
rcssmin (1.0.6)
redis (2.10.5)
requests (2.9.1)
requests-oauthlib (0.7.0)
requests-toolbelt (0.7.0)
rjsmin (1.0.12)
rsa (3.4.2)
Rx (1.6.1)
s3transfer (0.1.11)
saved-search (0.2)
selenium (2.46.0)
setuptools (20.7.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
snowflake-connector-python (1.6.2)
snowflake-sqlalchemy (1.1.1)
solrsitemap (1.0)
South (0.8.4)
Sphinx (1.3.3)
sphinx-rtd-theme (0.1.9)
SQLAlchemy (1.2.8)
sqlparse (0.2.1)
suds (0.4)
suds-jurko (0.6)
testfixtures (3.0.0)
tlslite (0.4.9)
typing (3.6.4)
ua-parser (0.7.3)
unicode-slugify (0.1)
unicodecsv (0.9.4)
urllib3 (1.22)
user-agents (1.1.0)
validate-email (1.2)
wheel (0.24.0)
wrapt (1.10.8)
xlrd (0.9.3)
XlsxWriter (0.8.4)
xxhash (1.0.1)
```

4. What did you do?
```
import re
import base64
from sqlalchemy.sql import select, column
from sqlalchemy import MetaData, Table, Column, Date, DateTime, Integer, func
from sqlalchemy import create_engine

from snowflake.sqlalchemy import URL
from secrets import SNOWFLAKE_KEY, SNOWFLAKE_USER, SNOWFLAKE_ACCOUNT

metadata = MetaData()

jobview_table = Table(
    'jobview', metadata,
    Column('server_datetime', DateTime(True)),
    Column('server_date', Date),
    Column('buid', Integer),
    snowflake_clusterby=['server_date'],
)

SNOWFLAKE=dict(
    app=dict(
        user=SNOWFLAKE_USER, account=SNOWFLAKE_ACCOUNT, private_key=SNOWFLAKE_KEY,
        role='sysadmin', region='us-east-1',
        database='test_db', schema='public', warehouse='ingest'))


def build_snowflake_url(db):
    snowflake_settings = dict(SNOWFLAKE[db])

    if 'private_key' in snowflake_settings:
        key = snowflake_settings['private_key']
        # Decode the raw PEM if the key looks like --- BEGIN ... ---
        if '---' in key:
            # Strip of the header and footer. base64 doesn't want those there.
            key = base64.decodestring(re.sub(r'---.*---', '', key))
            snowflake_settings['private_key'] = key

    return URL(**snowflake_settings)


def create_snowflake_engine(db):
    url = build_snowflake_url(db)
    engine = create_engine(url)
    return engine

engine = create_snowflake_engine('app')

def go():
    print 'connecting'
    with engine.begin() as connection:
        print 'connected'
        queryset = select([func.count(jobview_table.c['server_datetime'])]).where(column('buid') == 1L).limit(10)
        print 'running'
        results = connection.execute(queryset).fetchall()
        print 'done'
        print results
```

5. What did you expect to see?

Should have run the query.

6. What did you see instead?

```
connecting
connected
running
Traceback (most recent call last):
  File "<ipython-input-100-5f037b91a89a>", line 1, in <module>
    go2.go()
  File "go2.py", line 54, in go
    results = connection.execute(queryset).fetchall()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/snowflake/connector/cursor.py", line 542, in execute
    errvalue)
  File "/usr/local/lib/python2.7/dist-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001003 (42000): SQL compilation error:
syntax error line 3 at position 14 unexpected 'L'. [SQL: u'SELECT count(jobview.server_datetime) AS count_1 \nFROM jobview \nWHERE buid = %(buid_1)s\n LIMIT %(param_1)s'] [parameters: {u'param_1': 10, u'buid_1': 1L}] (Background on this error at: http://sqlalche.me/e/f405)
```

7. Can you set logging to DEBUG and collect the logs?

See attached.

**Comment by darrint** [comment]
[logs.txt](https://github.com/snowflakedb/snowflake-sqlalchemy/files/2093920/logs.txt)

**Comment by smtakeda** [comment]
Thanks for a bug report. This is an Python Connector issue, so I'll patch on https://github.com/snowflakedb/snowflake-connector-python.

**Comment by smtakeda** [comment]
https://github.com/snowflakedb/snowflake-connector-python/pull/91

**Comment by smtakeda** [comment]
Python connector 1.6.3 will have the fix.
